#!/usr/bin/env python3
"""Render an AST generated by parse.py into HTML."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import html

from parse import (
    ArrowBlock,
    Block,
    Body,
    Dialogue,
    Emphasis,
    Narration,
    Node,
    Paragraph,
    Prose,
    SectionBreak,
    Text,
    parse,
)


class RenderContext:
    """Context for rendering, tracking arrow block modifiers."""

    def __init__(self) -> None:
        self.arrow_modifiers: dict[int, List[Tuple[str, str]]] = {}

    def apply_arrow_blocks(self, body: Body) -> None:
        """Pre-process arrow blocks and track which items they apply to."""
        pending_arrows: List[Tuple[str, List[Tuple[str, str]]]] = []

        for i, item in enumerate(body.items):
            if isinstance(item, ArrowBlock):
                pending_arrows.append((item.tag, item.modifiers))
            else:
                # Apply pending arrows to this item if the tag matches
                if pending_arrows:
                    if isinstance(item, Paragraph) and any(tag == "p" for tag, _ in pending_arrows):
                        modifiers = []
                        for tag, mods in pending_arrows:
                            if tag == "p":
                                modifiers.extend(mods)
                        if modifiers:
                            self.arrow_modifiers[i] = modifiers
                        pending_arrows = [(tag, mods) for tag, mods in pending_arrows if tag != "p"]
                    elif isinstance(item, Block) and any(tag == item.tag for tag, _ in pending_arrows):
                        modifiers = []
                        for tag, mods in pending_arrows:
                            if tag == item.tag:
                                modifiers.extend(mods)
                        if modifiers:
                            self.arrow_modifiers[i] = modifiers
                        pending_arrows = [(tag, mods) for tag, mods in pending_arrows if tag != item.tag]

    def get_arrow_modifiers(self, index: int) -> List[Tuple[str, str]]:
        """Get arrow modifiers for a specific body item index."""
        return self.arrow_modifiers.get(index, [])


@dataclass
class RenderConfig:
    section_break_tag: str = "hr"
    section_break_class: str = "section-break"
    section_break_text: str = ""
    minor_section_break_tag: str = "p"
    minor_section_break_class: str = "minor-section-break"
    minor_section_break_text: str = ""
    not_inset_class: str = "not-inset"
    small_caps_class: str = "small-caps"
    dialog_space_class: str = "fwsp"

    @classmethod
    def from_path(cls, path: Path) -> "RenderConfig":
        if not path.exists():
            raise FileNotFoundError(path)

        raw = cls._load_config_file(path)
        if not isinstance(raw, dict):
            raise ValueError("Configuration file must contain an object at the top level")

        return cls(
            section_break_tag=raw.get("section_break_tag", cls.section_break_tag),
            section_break_class=raw.get("section_break_class", cls.section_break_class),
            section_break_text=raw.get("section_break_text", cls.section_break_text),
            minor_section_break_tag=raw.get("minor_section_break_tag", cls.minor_section_break_tag),
            minor_section_break_class=raw.get("minor_section_break_class", cls.minor_section_break_class),
            minor_section_break_text=raw.get("minor_section_break_text", cls.minor_section_break_text),
            not_inset_class=raw.get("not_inset_class", cls.not_inset_class),
            small_caps_class=raw.get("small_caps_class", cls.small_caps_class),
            dialog_space_class=raw.get("dialog_space_class", cls.dialog_space_class),
        )

    @classmethod
    def _load_config_file(cls, path: Path) -> Any:
        text = path.read_text(encoding="utf-8")
        return json.loads(text)


def load_config(path: Optional[Path] = None) -> RenderConfig:
    if path is not None:
        return RenderConfig.from_path(path)

    if Path("config.json").exists():
        return RenderConfig.from_path(Path("config.json"))

    return RenderConfig()


def render_html(ast: Block, config: RenderConfig) -> str:
    """Render an AST into HTML."""
    ctx = RenderContext()
    ctx.apply_arrow_blocks(ast.body)
    return render_block(ast, ctx, config, is_root=True)


def render_block(block: Block, ctx: RenderContext, config: RenderConfig, is_root: bool = False, inline: bool = False, is_first: bool = False) -> str:
    """Render a block element.
    
    Args:
        block: The block to render
        ctx: Rendering context
        is_root: Whether this is the root document block
        inline: Whether to render inline (don't wrap body content in <p> tags)
        is_first: Whether this block is the first in its parent body (affects not-inset)
    """
    if is_root:
        # Root document block - just render its body without the tag
        return render_body(block.body, ctx, config, is_first_in_parent=True)

    attrs = render_attributes(block.modifiers)
    
    # Determine if this is a purely inline tag
    inline_tags = {"span", "i", "b", "u", "em", "strong", "small", "code", "kbd", "var"}
    is_inline_tag = block.tag.lower() in inline_tags
    
    if inline or is_inline_tag:
        # Inline block - render body content directly without <p> wrapping
        inner = render_body_inline_content(block.body, config)
    else:
        # Block-level - wrap body content in <p> tags as needed
        inner = render_body(block.body, ctx, config, is_first_in_parent=is_first)
    tag = block.tag
    return f"<{tag}{attrs}>{inner}</{tag}>"


def render_body(body: Body, ctx: RenderContext, config: RenderConfig, is_first_in_parent: bool = False) -> str:
    """Render a body with its items."""
    lines: List[str] = []
    is_first_item = is_first_in_parent

    for i, item in enumerate(body.items):
        if isinstance(item, ArrowBlock):
            # Skip rendering arrow blocks
            continue
        elif isinstance(item, Paragraph):
            arrow_modifiers = ctx.get_arrow_modifiers(i)
            html = render_paragraph(item, is_first_item, arrow_modifiers, config)
            if html:  # Only add non-empty paragraphs
                lines.append(html)
                is_first_item = False
        elif isinstance(item, SectionBreak):
            html = render_section_break(item, config)
            lines.append(html)
            is_first_item = True  # Next item after section break is "first"

    return "\n".join(lines)


def render_body_inline(body: Body, ctx: RenderContext, config: RenderConfig) -> str:
    """Render a body for inline content (inside a block element)."""
    lines: List[str] = []
    is_first_para = True
    for item in body.items:
        if isinstance(item, ArrowBlock):
            continue
        elif isinstance(item, Paragraph):
            content = render_para_content(item, config)
            if content.strip():
                # First paragraph in an inline block still gets not-inset
                if is_first_para and config.not_inset_class != "":
                    lines.append(f'<p class="{config.not_inset_class}">{content}</p>')
                    is_first_para = False
                else:
                    lines.append(f"<p>{content}</p>")
        elif isinstance(item, SectionBreak):
            lines.append(render_section_break(item, config))
            is_first_para = True
    return "\n".join(lines)


def render_body_inline_content(body: Body, config: RenderConfig) -> str:
    """Render a body inline (for inline blocks like span, i, b)."""
    parts: List[str] = []
    for item in body.items:
        if isinstance(item, Paragraph):
            parts.append(render_para_content(item, config))
        elif isinstance(item, SectionBreak):
            parts.append(render_section_break(item, config))
    return "".join(parts)



def render_paragraph(para: Paragraph, is_first: bool = False, extra_modifiers: List[Tuple[str, str]] | None = None, config: RenderConfig = RenderConfig()) -> str:
    """Render a paragraph element."""
    if not para.items:
        return ""

    # Special case: if paragraph contains only a single block, render the block directly
    if len(para.items) == 1 and isinstance(para.items[0], Block):
        block = para.items[0]
        # Apply extra modifiers to the block
        if extra_modifiers:
            block.modifiers.extend(extra_modifiers)
        ctx = RenderContext()
        
        # Check if this is an inline block
        inline_tags = {"span", "i", "b", "u", "em", "strong", "small", "code", "kbd", "var"}
        is_inline = block.tag.lower() in inline_tags
        
        # Pass is_first flag to block rendering
        return render_block(block, ctx, config, inline=is_inline, is_first=is_first)

    content = render_para_content(para, config)
    if not content.strip():
        return ""

    modifiers: List[Tuple[str, str]] = []
    if is_first and config.not_inset_class != "":
        modifiers.append((".", config.not_inset_class))
    if extra_modifiers:
        modifiers.extend(extra_modifiers)

    attrs = render_attributes(modifiers)
    return f"<p{attrs}>{content}</p>"


def render_para_content(para: Paragraph, config: RenderConfig) -> str:
    """Render the content of a paragraph."""
    parts: List[str] = []
    ctx = RenderContext()
    for item in para.items:
        if isinstance(item, Prose):
            parts.append(render_prose(item, config))
        elif isinstance(item, Block):
            # Render blocks inline (without extra paragraph wrapping)
            # Blocks inside paragraphs are not "first" in their parent
            parts.append(render_block(item, ctx, config, inline=True, is_first=False))
        elif isinstance(item, Emphasis):
            parts.append(render_emphasis(item, config))
        elif isinstance(item, Text):
            parts.append(item.content)
    return "".join(parts)


def render_prose(prose: Prose, config: RenderConfig) -> str:
    """Render prose with narration and dialogue."""
    parts: List[str] = []
    for i, part in enumerate(prose.parts):
        if isinstance(part, Narration):
            if i > 0:
                # After dialogue, add spacing before narration
                parts.append(f'<span class="{config.dialog_space_class}"> </span>— ')
            parts.append(render_narration(part, config))
        elif isinstance(part, Dialogue):
            # Before dialogue, add em-dash and spacing
            parts.append(f' —<span class="{config.dialog_space_class}"> </span>')
            parts.append(render_dialogue(part, config))
    return "".join(parts)


def render_narration(narration: Narration, config: RenderConfig) -> str:
    """Render narration content."""
    content = render_content_items(narration.items, config)
    # Strip space from narration if it starts with one
    return content.strip(" ")


def render_dialogue(dialogue: Dialogue, config: RenderConfig) -> str:
    """Render dialogue content."""
    content = render_content_items(dialogue.items, config)
    # Strip space from dialogue if it starts with one
    return content.strip(" ")


def render_content_items(items: List[Node], config: RenderConfig) -> str:
    """Render a list of content items."""
    ctx = RenderContext()
    parts: List[str] = []
    for item in items:
        if isinstance(item, Text):
            parts.append(html.escape(item.content))
        elif isinstance(item, Block):
            # Render blocks inline within narration/dialogue
            # Blocks inside narration/dialogue are not "first" in their parent
            parts.append(render_block(item, ctx, config, inline=True, is_first=False))
        elif isinstance(item, Emphasis):
            parts.append(render_emphasis(item, config))
        elif isinstance(item, Paragraph):
            parts.append(render_para_content(item, config))
    return "".join(parts)


def render_emphasis(emphasis: Emphasis, config: RenderConfig) -> str:
    """Render emphasis (italics, bold, underline, etc)."""
    marker = emphasis.marker
    content = render_para_content(emphasis.content, config)

    if marker == "*":
        return f"<i>{content}</i>"
    elif marker == "**":
        return f"<b>{content}</b>"
    elif marker == "***":
        return f"<b><i>{content}</i></b>"
    elif marker == "_":
        return f"<u>{content}</u>"
    elif marker == "~":
        return f"<s>{content}</s>"
    elif marker == "$":
        return f"<span class=\"{config.small_caps_class}\">{content}</span>"
    else:
        return content


def render_section_break(section_break: SectionBreak, config: RenderConfig) -> str:
    """Render a section break."""
    if section_break.marker == "~":
        return f'<{config.section_break_tag} class="{config.section_break_class}">{config.section_break_text}</{config.section_break_tag}>'
    elif section_break.marker == ">":
        return f'<{config.minor_section_break_tag} class="{config.minor_section_break_class}">{config.minor_section_break_text}</{config.minor_section_break_tag}>'
    return ""


def render_attributes(modifiers: List[Tuple[str, str]]) -> str:
    """Render HTML attributes from modifiers."""
    classes: List[str] = []
    ids: List[str] = []

    for marker, identifier in modifiers:
        if marker == ".":
            classes.append(identifier)
        elif marker == "#":
            ids.append(identifier)

    attrs: List[str] = []
    if classes:
        attrs.append(f'class="{" ".join(classes)}"')
    if ids:
        # Use only the first ID, as HTML only supports one ID per element
        attrs.append(f'id="{ids[0]}"')

    return f" {' '.join(attrs)}" if attrs else ""


def main() -> int:
    parser = argparse.ArgumentParser(description="Render an AST to HTML")
    parser.add_argument("source", nargs="?", help="input file; reads from stdin if omitted")
    parser.add_argument("--output", "-o", help="output file; writes to stdout if omitted")
    parser.add_argument("--template", "-t", help="HTML template file with {{content}} placeholder")
    parser.add_argument("--config", "-c", help="JSON config file")
    args = parser.parse_args()

    if args.source:
        source_text = Path(args.source).read_text(encoding="utf-8")
    else:
        source_text = sys.stdin.read()

    config = load_config(Path(args.config)) if args.config else load_config()

    template = "{{content}}"
    if args.template:
        template = Path(args.template).read_text(encoding="utf8")
        if "{{content}}" not in template:
            print("Error: Template file must contain {{content}} placeholder", file=sys.stderr)
            return 1

    ast = parse(source_text)
    html = render_html(ast, config)

    templated_html = template.replace("{{content}}", html)

    if args.output:
        Path(args.output).write_text(templated_html, encoding="utf-8")
    else:
        try:
            print(templated_html)
        except UnicodeEncodeError:
            # Fallback for console encodings that don't support Unicode
            # Write to stdout using UTF-8 without errors
            sys.stdout.buffer.write(templated_html.encode("utf-8"))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
