#!/usr/bin/env python3
"""Render an AST generated by parse.py into HTML."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import html

from parse import (
    OutlineBlock,
    InlineBlock,
    Body,
    Dialogue,
    Emphasis,
    Narration,
    Node,
    Paragraph,
    Break,
    Text,
    parse,
)


class RenderContext:
    """Context for rendering."""

    def __init__(self) -> None:
        pass

@dataclass
class BreakType:
    tag: Optional[str]
    class_attr: Optional[str]
    text: Optional[str]

@dataclass
class RenderConfig:
    break_types: Dict[str, BreakType] = None
    not_inset_class: str = "not-inset"
    small_caps_class: str = "small-caps"
    dialog_space_class: str = "fwsp"

    @classmethod
    def from_path(cls, path: Path) -> "RenderConfig":
        if not path.exists():
            raise FileNotFoundError(path)

        raw = cls._load_config_file(path)
        if not isinstance(raw, dict):
            raise ValueError("Configuration file must contain an object at the top level")

        return cls(
            break_types={k: BreakType(tag=v.get("tag", None), class_attr=v.get("class", None), text=v.get("text", None)) for k, v in raw.get("breaks", {}).items()},
            not_inset_class=raw.get("not_inset_class", cls.not_inset_class),
            small_caps_class=raw.get("small_caps_class", cls.small_caps_class),
            dialog_space_class=raw.get("dialog_space_class", cls.dialog_space_class),
        )

    @classmethod
    def _load_config_file(cls, path: Path) -> Any:
        text = path.read_text(encoding="utf-8")
        return json.loads(text)


def load_config(path: Optional[Path] = None) -> RenderConfig:
    if path is not None:
        return RenderConfig.from_path(path)

    if Path("config.json").exists():
        return RenderConfig.from_path(Path("config.json"))

    return RenderConfig()


def render_html(ast: OutlineBlock, config: RenderConfig) -> str:
    """Render an AST into HTML."""
    ctx = RenderContext()
    return render_outline_block(ast, ctx, config, is_root=True)


def render_outline_block(block: OutlineBlock, ctx: RenderContext, config: RenderConfig, is_root: bool = False, is_first: bool = False) -> str:
    """Render a block element.
    
    Args:
        block: The block to render
        ctx: Rendering context
        is_root: Whether this is the root document block
        is_first: Whether this block is the first in its parent body (affects not-inset)
    """
    if is_root:
        # Root document block - just render its body without the tag
        return render_body(block.body, ctx, config, is_first_in_parent=True)

    attrs = render_attributes(block.modifiers)
    
    inner = render_body(block.body, ctx, config, is_first_in_parent=is_first)

    return f"<div{attrs}>{inner}</div>"

def render_inline_block(block: InlineBlock, ctx: RenderContext, config: RenderConfig) -> str:
    """Render an inline block element."""
    attrs = render_attributes(block.modifiers)
    inner = render_para_content(block.para, config)
    return f"<span{attrs}>{inner}</span>"

def render_body(body: Body, ctx: RenderContext, config: RenderConfig, is_first_in_parent: bool = False) -> str:
    """Render a body with its items."""
    lines: List[str] = []
    is_first_item = is_first_in_parent

    for i, item in enumerate(body.items):
        if isinstance(item, Paragraph):
            html = render_paragraph(item, is_first_item, None, config)
            if html:  # Only add non-empty paragraphs
                lines.append(html)
                is_first_item = False
        if isinstance(item, OutlineBlock):
            html = render_outline_block(item, ctx, config, is_root=False, is_first=is_first_item)
            lines.append(html)
            is_first_item = True
        elif isinstance(item, Break):
            html = render_section_break(item, config)
            lines.append(html)
            is_first_item = True  # Next item after section break is "first"

    return "\n".join(lines)

def render_body_inline_content(body: Body, config: RenderConfig) -> str:
    """Render a body inline (for inline blocks like span, i, b)."""
    parts: List[str] = []
    for item in body.items:
        if isinstance(item, Paragraph):
            parts.append(render_para_content(item, config))
        elif isinstance(item, Break):
            parts.append(render_section_break(item, config))
    return "".join(parts)



def render_paragraph(para: Paragraph, is_first: bool = False, extra_modifiers: List[Tuple[str, str]] | None = None, config: RenderConfig = RenderConfig()) -> str:
    """Render a paragraph element."""
    if not para.parts:
        return ""

    content = render_para_content(para, config)
    if not content.strip():
        return ""

    modifiers: List[str] = []
    if is_first and config.not_inset_class != "":
        modifiers.append((".", config.not_inset_class))
    if extra_modifiers:
        modifiers.extend(extra_modifiers)

    attrs = render_attributes(modifiers)
    return f"<p{attrs}>{content}</p>"


def render_para_content(para: Paragraph, config: RenderConfig) -> str:
    """Render prose with narration and dialogue."""
    parts: List[str] = []
    for i, part in enumerate(para.parts):
        if isinstance(part, Narration):
            if i > 0:
                # After dialogue, add spacing before narration
                parts.append(f'<span class="{config.dialog_space_class}"> </span>— ')
            parts.append(render_narration(part, config))
        elif isinstance(part, Dialogue):
            # Before dialogue, add em-dash and spacing
            parts.append(f' —<span class="{config.dialog_space_class}"> </span>')
            parts.append(render_dialogue(part, config))
    return "".join(parts)


def render_narration(narration: Narration, config: RenderConfig) -> str:
    """Render narration content."""
    content = render_content_items(narration.items, config)
    # Strip space from narration if it starts with one
    return content.strip(" ")


def render_dialogue(dialogue: Dialogue, config: RenderConfig) -> str:
    """Render dialogue content."""
    content = render_content_items(dialogue.items, config)
    # Strip space from dialogue if it starts with one
    return content.strip(" ")


def render_content_items(items: List[Node], config: RenderConfig) -> str:
    """Render a list of content items."""
    ctx = RenderContext()
    parts: List[str] = []
    for item in items:
        if isinstance(item, Text):
            parts.append(html.escape(item.content))
        elif isinstance(item, InlineBlock):
            # Render blocks inline within narration/dialogue
            # Blocks inside narration/dialogue are not "first" in their parent
            parts.append(render_inline_block(item, ctx, config))
        elif isinstance(item, Emphasis):
            parts.append(render_emphasis(item, config))
        elif isinstance(item, Paragraph):
            parts.append(render_para_content(item, config))
    return "".join(parts)


def render_emphasis(emphasis: Emphasis, config: RenderConfig) -> str:
    """Render emphasis (italics, bold, underline, etc)."""
    marker = emphasis.marker
    content = render_para_content(emphasis.content, config)

    if marker == "*":
        return f"<i>{content}</i>"
    elif marker == "**":
        return f"<b>{content}</b>"
    elif marker == "***":
        return f"<b><i>{content}</i></b>"
    elif marker == "_":
        return f"<u>{content}</u>"
    elif marker == "~":
        return f"<s>{content}</s>"
    elif marker == "$":
        return f"<span class=\"{config.small_caps_class}\">{content}</span>"
    else:
        return content


def render_section_break(section_break: Break, config: RenderConfig) -> str:
    """Render a section break."""
    for break_marker, break_type in config.break_types.items():
        if section_break.marker == break_marker and break_type.tag is not None:
            attrs = render_attributes([(".", break_type.class_attr)] if break_type.class_attr else [])
            return f'<{break_type.tag}{attrs}>{break_type.text or ""}</{break_type.tag}>'
    return ""


def render_attributes(modifiers: List[Tuple[str, str]]) -> str:
    """Render HTML attributes from modifiers."""
    classes: List[str] = []
    ids: List[str] = []

    for marker, identifier in modifiers:
        if marker == ".":
            classes.append(identifier)
        elif marker == "#":
            ids.append(identifier)

    attrs: List[str] = []
    if classes:
        attrs.append(f'class="{" ".join(classes)}"')
    if ids:
        # Use only the first ID, as HTML only supports one ID per element
        attrs.append(f'id="{ids[0]}"')

    return f" {' '.join(attrs)}" if attrs else ""


def main() -> int:
    parser = argparse.ArgumentParser(description="Render an AST to HTML")
    parser.add_argument("source", nargs="?", help="input file; reads from stdin if omitted")
    parser.add_argument("--output", "-o", help="output file; writes to stdout if omitted")
    parser.add_argument("--template", "-t", help="HTML template file with {{content}} placeholder")
    parser.add_argument("--config", "-c", help="JSON config file")
    args = parser.parse_args()

    if args.source:
        source_text = Path(args.source).read_text(encoding="utf-8")
    else:
        source_text = sys.stdin.read()

    config = load_config(Path(args.config)) if args.config else load_config()

    template = "{{content}}"
    if args.template:
        template = Path(args.template).read_text(encoding="utf8")
        if "{{content}}" not in template:
            print("Error: Template file must contain {{content}} placeholder", file=sys.stderr)
            return 1

    ast = parse(source_text)
    html = render_html(ast, config)

    templated_html = template.replace("{{content}}", html)

    if args.output:
        Path(args.output).write_text(templated_html, encoding="utf-8")
    else:
        try:
            print(templated_html)
        except UnicodeEncodeError:
            # Fallback for console encodings that don't support Unicode
            # Write to stdout using UTF-8 without errors
            sys.stdout.buffer.write(templated_html.encode("utf-8"))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
